import { defineTheme } from '../define';

/**
 * Part 1 — Cute (6), Girls (7), Boys (7), Cars (5) = 25 themes.
 * All palettes and artwork are original compositions.
 */

export const PART1_THEMES = [
  // ────────────────────────────── CUTE ──────────────────────────────
  defineTheme({
    id: 'pink-hearts',
    name: 'Pink Hearts',
    category: 'cute',
    description: 'Blush gradients with floating hearts and polaroid memories.',
    colors: {
      bg1: '#ffe4f0',
      bg2: '#ffc2dd',
      surface: 'rgba(255,255,255,0.86)',
      text: '#5f2145',
      muted: '#a2597f',
      accent: '#ff4d94',
      accent2: '#ff9ec7',
      border: 'rgba(255,77,148,0.24)',
    },
    headingFont: 'dancing',
    bodyFont: 'quicksand',
    background: 'soft-glow',
    decorations: 'hearts',
    decorDensity: 'medium',
    motion: 'float',
    card: 'glass',
    button: 'pill',
    photo: 'polaroid',
    confetti: ['#ff4d94', '#ff9ec7', '#ffd6e7', '#ffffff'],
  }),
  defineTheme({
    id: 'soft-pastel',
    name: 'Soft Pastel',
    category: 'cute',
    description: 'Gentle pastel washes with drifting bubbles and a clean carousel.',
    colors: {
      bg1: '#fdf3ff',
      bg2: '#e3f2fd',
      surface: 'rgba(255,255,255,0.9)',
      text: '#4a3f63',
      muted: '#8b81a6',
      accent: '#8f7bff',
      accent2: '#7fd8ff',
      border: 'rgba(143,123,255,0.22)',
    },
    headingFont: 'quicksand',
    bodyFont: 'poppins',
    background: 'dream-gradient',
    decorations: 'bubbles',
    decorDensity: 'low',
    motion: 'rise',
    card: 'glass',
    button: 'pill',
    photo: 'carousel',
    confetti: ['#8f7bff', '#7fd8ff', '#ffc6e5', '#fff3b0'],
  }),
  defineTheme({
    id: 'candy-pop',
    name: 'Candy Pop',
    category: 'cute',
    description: 'Candy stripes, playful script type and a colorful photo wall.',
    colors: {
      bg1: '#fff5f5',
      bg2: '#ffe0ec',
      surface: 'rgba(255,255,255,0.92)',
      text: '#71294f',
      muted: '#b35784',
      accent: '#ff6b9d',
      accent2: '#ffd166',
      border: 'rgba(255,107,157,0.26)',
    },
    headingFont: 'pacifico',
    bodyFont: 'quicksand',
    background: 'candy-stripes',
    decorations: 'confetti',
    decorDensity: 'high',
    motion: 'drift',
    card: 'solid',
    button: 'glossy',
    photo: 'wall',
    confetti: ['#ff6b9d', '#ffd166', '#6bd3ff', '#b28dff', '#7be495'],
  }),
  defineTheme({
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'cute',
    description: 'Bouncy gum-pink dreamscape with rising bubbles.',
    colors: {
      bg1: '#ffdff0',
      bg2: '#ffb8e0',
      surface: 'rgba(255,255,255,0.85)',
      text: '#6d1f52',
      muted: '#b2588f',
      accent: '#ff2e97',
      accent2: '#ff8ac9',
      border: 'rgba(255,46,151,0.24)',
    },
    headingFont: 'lobster',
    bodyFont: 'quicksand',
    background: 'dream-gradient',
    decorations: 'bubbles',
    decorDensity: 'medium',
    motion: 'rise',
    card: 'glass',
    button: 'glossy',
    photo: 'carousel',
    confetti: ['#ff2e97', '#ff8ac9', '#ffd1ea', '#c9f7ff'],
  }),
  defineTheme({
    id: 'cloud-nine',
    name: 'Cloud Nine',
    category: 'cute',
    description: 'Fluffy clouds and a soft sky of polaroids.',
    colors: {
      bg1: '#eaf6ff',
      bg2: '#d3ecff',
      surface: 'rgba(255,255,255,0.92)',
      text: '#2f4a66',
      muted: '#6d8dad',
      accent: '#4aa8ff',
      accent2: '#a8d8ff',
      border: 'rgba(74,168,255,0.22)',
    },
    headingFont: 'quicksand',
    bodyFont: 'quicksand',
    background: 'clouds',
    decorations: 'clouds',
    decorDensity: 'low',
    motion: 'drift',
    card: 'solid',
    button: 'pill',
    photo: 'polaroid',
    confetti: ['#4aa8ff', '#a8d8ff', '#ffffff', '#ffe9a8'],
  }),
  defineTheme({
    id: 'kawaii-sky',
    name: 'Kawaii Sky',
    category: 'cute',
    description: 'Pastel sky with twinkling sparkles and stacked memory cards.',
    colors: {
      bg1: '#fff0f6',
      bg2: '#e8e2ff',
      surface: 'rgba(255,255,255,0.88)',
      text: '#584070',
      muted: '#9a86b3',
      accent: '#ff7ab8',
      accent2: '#9d7bff',
      border: 'rgba(255,122,184,0.24)',
    },
    headingFont: 'quicksand',
    bodyFont: 'poppins',
    background: 'soft-glow',
    decorations: 'sparkles',
    decorDensity: 'medium',
    motion: 'sparkle',
    card: 'glass',
    button: 'pill',
    photo: 'stack',
    confetti: ['#ff7ab8', '#9d7bff', '#7fd8ff', '#fff3b0'],
  }),

  // ────────────────────────────── GIRLS ──────────────────────────────
  defineTheme({
    id: 'pink-glam',
    name: 'Pink Glam',
    category: 'girls',
    description: 'High-shine pink glamour with sparkle dust and elegant serifs.',
    colors: {
      bg1: '#ffd9ea',
      bg2: '#f7a8cf',
      surface: 'rgba(255,255,255,0.88)',
      text: '#661849',
      muted: '#a8578a',
      accent: '#e91e8c',
      accent2: '#ffb3d9',
      border: 'rgba(233,30,140,0.26)',
    },
    headingFont: 'playfair',
    bodyFont: 'poppins',
    background: 'soft-glow',
    decorations: 'sparkles',
    decorDensity: 'high',
    motion: 'sparkle',
    card: 'glass',
    button: 'gradient',
    photo: 'carousel',
    confetti: ['#e91e8c', '#ffb3d9', '#ffd700', '#ffffff'],
  }),
  defineTheme({
    id: 'luxury-pink',
    name: 'Luxury Pink',
    category: 'girls',
    description: 'Deep plum velvet with champagne-gold detailing.',
    colors: {
      bg1: '#3d0f2e',
      bg2: '#6b1247',
      surface: 'rgba(84,22,60,0.62)',
      text: '#ffe9f4',
      muted: '#d9a1c2',
      accent: '#ffb3d1',
      accent2: '#e8c56a',
      border: 'rgba(255,179,209,0.28)',
    },
    headingFont: 'cormorant',
    bodyFont: 'montserrat',
    background: 'velvet',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'ornate',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#ffb3d1', '#e8c56a', '#ffffff', '#a14a7d'],
  }),
  defineTheme({
    id: 'floral-garden',
    name: 'Floral Garden',
    category: 'girls',
    description: 'Painterly florals with drifting petals and polaroid frames.',
    colors: {
      bg1: '#fdf6f0',
      bg2: '#f6dfd3',
      surface: 'rgba(255,255,255,0.9)',
      text: '#5c3a34',
      muted: '#a07f74',
      accent: '#d95f76',
      accent2: '#8fae7e',
      border: 'rgba(217,95,118,0.22)',
    },
    headingFont: 'greatvibes',
    bodyFont: 'cormorant',
    background: 'floral',
    decorations: 'petals',
    decorDensity: 'medium',
    motion: 'fall',
    card: 'solid',
    button: 'outline',
    photo: 'polaroid',
    confetti: ['#d95f76', '#8fae7e', '#f2c4ce', '#fff6e9'],
  }),
  defineTheme({
    id: 'elegant-rose',
    name: 'Elegant Rose',
    category: 'girls',
    description: 'Dusty rose minimalism for a timeless keepsake timeline.',
    colors: {
      bg1: '#fbf3f2',
      bg2: '#eed7d5',
      surface: 'rgba(255,255,255,0.94)',
      text: '#57353c',
      muted: '#9b7379',
      accent: '#b25d6b',
      accent2: '#d9a5ac',
      border: 'rgba(178,93,107,0.22)',
    },
    headingFont: 'marcellus',
    bodyFont: 'poppins',
    background: 'soft-glow',
    decorations: 'petals',
    decorDensity: 'low',
    motion: 'fall',
    card: 'ornate',
    button: 'outline',
    photo: 'timeline',
    confetti: ['#b25d6b', '#d9a5ac', '#f4dfe0', '#ffffff'],
  }),
  defineTheme({
    id: 'sparkle-night',
    name: 'Sparkle Night',
    category: 'girls',
    description: 'A starry evening dress-up with shimmering highlights.',
    colors: {
      bg1: '#1a1033',
      bg2: '#341b5c',
      surface: 'rgba(46,26,84,0.62)',
      text: '#f3e9ff',
      muted: '#b9a6e0',
      accent: '#c084fc',
      accent2: '#f0abfc',
      border: 'rgba(192,132,252,0.3)',
    },
    headingFont: 'playfair',
    bodyFont: 'poppins',
    background: 'stars',
    decorations: 'sparkles',
    decorDensity: 'high',
    motion: 'sparkle',
    card: 'minimal',
    button: 'gradient',
    photo: 'carousel',
    confetti: ['#c084fc', '#f0abfc', '#facc15', '#ffffff'],
  }),
  defineTheme({
    id: 'fashion-night',
    name: 'Fashion Night',
    category: 'girls',
    description: 'Runway spotlight drama with bold condensed typography.',
    colors: {
      bg1: '#0d0d12',
      bg2: '#1f1430',
      surface: 'rgba(28,22,44,0.66)',
      text: '#f5f0ff',
      muted: '#a99fc4',
      accent: '#f43f8e',
      accent2: '#c084fc',
      border: 'rgba(244,63,142,0.28)',
    },
    headingFont: 'bebas',
    bodyFont: 'montserrat',
    background: 'spotlight',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'glass',
    button: 'neon',
    photo: 'slideshow',
    confetti: ['#f43f8e', '#c084fc', '#ffffff', '#facc15'],
  }),
  defineTheme({
    id: 'dreamy',
    name: 'Dreamy',
    category: 'girls',
    description: 'Soft-focus bokeh lights drifting through a dream sequence.',
    colors: {
      bg1: '#efe9ff',
      bg2: '#d8ccfa',
      surface: 'rgba(255,255,255,0.85)',
      text: '#443563',
      muted: '#8a7aab',
      accent: '#9b7bff',
      accent2: '#ffb3e6',
      border: 'rgba(155,123,255,0.24)',
    },
    headingFont: 'cormorant',
    bodyFont: 'quicksand',
    background: 'bokeh',
    decorations: 'bubbles',
    decorDensity: 'medium',
    motion: 'float',
    card: 'glass',
    button: 'gradient',
    photo: 'slideshow',
    confetti: ['#9b7bff', '#ffb3e6', '#b3e6ff', '#ffffff'],
  }),

  // ────────────────────────────── BOYS ──────────────────────────────
  defineTheme({
    id: 'blue-neon',
    name: 'Blue Neon',
    category: 'boys',
    description: 'Electric cyan neon on deep navy with grid glow.',
    colors: {
      bg1: '#050b1e',
      bg2: '#0b1e42',
      surface: 'rgba(10,26,58,0.66)',
      text: '#e6f6ff',
      muted: '#88b6d9',
      accent: '#00d4ff',
      accent2: '#4d7cff',
      border: 'rgba(0,212,255,0.32)',
    },
    headingFont: 'orbitron',
    bodyFont: 'montserrat',
    background: 'neon-grid',
    decorations: 'stars',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'neon',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#00d4ff', '#4d7cff', '#9bf0ff', '#ffffff'],
  }),
  defineTheme({
    id: 'midnight-gold',
    name: 'Midnight Gold',
    category: 'boys',
    description: 'Black-tie midnight velvet with restrained gold accents.',
    colors: {
      bg1: '#0c0c10',
      bg2: '#20180a',
      surface: 'rgba(32,26,14,0.62)',
      text: '#f7efdc',
      muted: '#c2ae82',
      accent: '#d9b45c',
      accent2: '#f2d896',
      border: 'rgba(217,180,92,0.3)',
    },
    headingFont: 'cinzel',
    bodyFont: 'montserrat',
    background: 'velvet',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'ornate',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#d9b45c', '#f2d896', '#ffffff', '#5a4a20'],
  }),
  defineTheme({
    id: 'sport-energy',
    name: 'Sport Energy',
    category: 'boys',
    description: 'Dynamic diagonal stripes and high-contrast sports styling.',
    colors: {
      bg1: '#f4f7fb',
      bg2: '#dbe7f5',
      surface: 'rgba(255,255,255,0.94)',
      text: '#17293f',
      muted: '#5c7391',
      accent: '#ff5c2b',
      accent2: '#1f7ae0',
      border: 'rgba(31,122,224,0.24)',
    },
    headingFont: 'montserrat',
    bodyFont: 'montserrat',
    background: 'stripes-diag',
    decorations: 'confetti',
    decorDensity: 'low',
    motion: 'drift',
    card: 'solid',
    button: 'gradient',
    photo: 'wall',
    confetti: ['#ff5c2b', '#1f7ae0', '#ffd166', '#ffffff'],
  }),
  defineTheme({
    id: 'adventure-trail',
    name: 'Adventure Trail',
    category: 'boys',
    description: 'Mountains, paper textures and an explorer timeline.',
    colors: {
      bg1: '#f3ede1',
      bg2: '#dbc9a8',
      surface: 'rgba(255,252,244,0.94)',
      text: '#42351f',
      muted: '#84704e',
      accent: '#a2652c',
      accent2: '#5c7a4a',
      border: 'rgba(162,101,44,0.26)',
    },
    headingFont: 'bebas',
    bodyFont: 'quicksand',
    background: 'mountains',
    decorations: 'leaves',
    decorDensity: 'low',
    motion: 'sway',
    card: 'paper',
    button: 'outline',
    photo: 'timeline',
    confetti: ['#a2652c', '#5c7a4a', '#e0c9a0', '#ffffff'],
  }),
  defineTheme({
    id: 'grand-prix',
    name: 'Grand Prix',
    category: 'boys',
    description: 'Race-night energy with speed streaks and sharp type.',
    colors: {
      bg1: '#0a0a0f',
      bg2: '#241012',
      surface: 'rgba(34,16,18,0.66)',
      text: '#fff1ec',
      muted: '#d09a8a',
      accent: '#ff2d2d',
      accent2: '#ffb703',
      border: 'rgba(255,45,45,0.32)',
    },
    headingFont: 'orbitron',
    bodyFont: 'montserrat',
    background: 'speed',
    decorations: 'confetti',
    decorDensity: 'low',
    motion: 'drift',
    card: 'neon',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#ff2d2d', '#ffb703', '#ffffff', '#ff7a45'],
  }),
  defineTheme({
    id: 'street-style',
    name: 'Street Style',
    category: 'boys',
    description: 'Concrete greys and brushed metal with raw street attitude.',
    colors: {
      bg1: '#20242a',
      bg2: '#3a4048',
      surface: 'rgba(46,52,60,0.7)',
      text: '#eef2f6',
      muted: '#9aa6b2',
      accent: '#f5f5f5',
      accent2: '#ffd166',
      border: 'rgba(255,255,255,0.22)',
    },
    headingFont: 'bebas',
    bodyFont: 'space',
    background: 'metal',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'solid',
    button: 'outline',
    photo: 'wall',
    confetti: ['#f5f5f5', '#ffd166', '#9aa6b2', '#3a4048'],
  }),
  defineTheme({
    id: 'dark-luxury',
    name: 'Dark Luxury',
    category: 'boys',
    description: 'Understated charcoal sophistication with subtle shine.',
    colors: {
      bg1: '#101014',
      bg2: '#1c1c24',
      surface: 'rgba(28,28,36,0.72)',
      text: '#f4f1ea',
      muted: '#a09a8c',
      accent: '#c9a86a',
      accent2: '#8a8f98',
      border: 'rgba(201,168,106,0.26)',
    },
    headingFont: 'marcellus',
    bodyFont: 'space',
    background: 'velvet',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'minimal',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#c9a86a', '#f4f1ea', '#8a8f98', '#5a5548'],
  }),

  // ────────────────────────────── CARS ──────────────────────────────
  defineTheme({
    id: 'racing-checkers',
    name: 'Racing Checkers',
    category: 'cars',
    description: 'Classic checkered flag motif with pit-lane filmstrip.',
    colors: {
      bg1: '#f5f5f5',
      bg2: '#d9d9d9',
      surface: 'rgba(255,255,255,0.95)',
      text: '#141414',
      muted: '#5c5c5c',
      accent: '#e10600',
      accent2: '#141414',
      border: 'rgba(20,20,20,0.2)',
    },
    headingFont: 'bebas',
    bodyFont: 'montserrat',
    background: 'checkers',
    decorations: 'confetti',
    decorDensity: 'low',
    motion: 'drift',
    card: 'solid',
    button: 'minimal',
    photo: 'filmstrip',
    confetti: ['#e10600', '#141414', '#ffffff', '#9e9e9e'],
  }),
  defineTheme({
    id: 'supercar',
    name: 'Supercar',
    category: 'cars',
    description: 'Matte black supercar lines traced in acid neon.',
    colors: {
      bg1: '#0b0b0d',
      bg2: '#1a1d12',
      surface: 'rgba(26,29,18,0.66)',
      text: '#f6ffe8',
      muted: '#a8b58c',
      accent: '#c6ff3d',
      accent2: '#8affd1',
      border: 'rgba(198,255,61,0.3)',
    },
    headingFont: 'orbitron',
    bodyFont: 'space',
    background: 'speed',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'drift',
    card: 'neon',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#c6ff3d', '#8affd1', '#ffffff', '#4a5320'],
  }),
  defineTheme({
    id: 'garage',
    name: 'Garage',
    category: 'cars',
    description: 'Workshop toolboard vibes with steel textures and grit.',
    colors: {
      bg1: '#2b2f33',
      bg2: '#4a5158',
      surface: 'rgba(48,54,60,0.72)',
      text: '#eef1f3',
      muted: '#a4adb5',
      accent: '#ff8c1a',
      accent2: '#59b3f0',
      border: 'rgba(255,140,26,0.28)',
    },
    headingFont: 'bebas',
    bodyFont: 'space',
    background: 'metal',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'solid',
    button: 'outline',
    photo: 'filmstrip',
    confetti: ['#ff8c1a', '#59b3f0', '#eef1f3', '#4a5158'],
  }),
  defineTheme({
    id: 'speed-run',
    name: 'Speed Run',
    category: 'cars',
    description: 'Motion-blur streaks with a high-speed photo wall.',
    colors: {
      bg1: '#08080c',
      bg2: '#131a2b',
      surface: 'rgba(19,26,43,0.68)',
      text: '#eef4ff',
      muted: '#8fa3c4',
      accent: '#3d8bff',
      accent2: '#00e5ff',
      border: 'rgba(61,139,255,0.3)',
    },
    headingFont: 'orbitron',
    bodyFont: 'montserrat',
    background: 'speed',
    decorations: 'stars',
    decorDensity: 'low',
    motion: 'drift',
    card: 'glass',
    button: 'gradient',
    photo: 'wall',
    confetti: ['#3d8bff', '#00e5ff', '#ffffff', '#1b2a4a'],
  }),
  defineTheme({
    id: 'night-drive',
    name: 'Night Drive',
    category: 'cars',
    description: 'City lights through a windshield in a late-night slideshow.',
    colors: {
      bg1: '#0a0f1c',
      bg2: '#16213e',
      surface: 'rgba(22,33,62,0.6)',
      text: '#e8f1ff',
      muted: '#8ea0c0',
      accent: '#7f5af0',
      accent2: '#4cc9f0',
      border: 'rgba(127,90,240,0.32)',
    },
    headingFont: 'space',
    bodyFont: 'montserrat',
    background: 'bokeh',
    decorations: 'bubbles',
    decorDensity: 'low',
    motion: 'float',
    card: 'glass',
    button: 'gradient',
    photo: 'slideshow',
    confetti: ['#7f5af0', '#4cc9f0', '#ffffff', '#2b2d42'],
  }),
];
