import { defineTheme } from '../define';

/**
 * Part 3 — Celebration (5), Elegant (5), Friendship (5), Special (8) = 23 themes.
 * All palettes and artwork are original compositions.
 */

export const PART3_THEMES = [
  // ──────────────────────────── CELEBRATION ────────────────────────────
  defineTheme({
    id: 'confetti-party',
    name: 'Confetti Party',
    category: 'celebration',
    description: 'The classic birthday party — confetti everywhere and big smiles.',
    colors: {
      bg1: '#fff7ed',
      bg2: '#ffd9c2',
      surface: 'rgba(255,255,255,0.92)',
      text: '#5a2317',
      muted: '#a5573b',
      accent: '#ff5c39',
      accent2: '#ffc53d',
      border: 'rgba(255,92,57,0.24)',
    },
    headingFont: 'lobster',
    bodyFont: 'quicksand',
    background: 'confetti-flat',
    decorations: 'confetti',
    decorDensity: 'high',
    motion: 'fall',
    card: 'solid',
    button: 'gradient',
    photo: 'wall',
    confetti: ['#ff5c39', '#ffc53d', '#38b6ff', '#7bd389', '#e879f9'],
  }),
  defineTheme({
    id: 'balloon-bash',
    name: 'Balloon Bash',
    category: 'celebration',
    description: 'Bunches of balloons rising into a sunny sky.',
    colors: {
      bg1: '#eef6ff',
      bg2: '#cfe4ff',
      surface: 'rgba(255,255,255,0.92)',
      text: '#1e3a5f',
      muted: '#607d9e',
      accent: '#3b82f6',
      accent2: '#fb7185',
      border: 'rgba(59,130,246,0.22)',
    },
    headingFont: 'pacifico',
    bodyFont: 'quicksand',
    background: 'soft-glow',
    decorations: 'balloons',
    decorDensity: 'high',
    motion: 'rise',
    card: 'glass',
    button: 'glossy',
    photo: 'carousel',
    confetti: ['#3b82f6', '#fb7185', '#fbbf24', '#34d399'],
  }),
  defineTheme({
    id: 'fireworks-night',
    name: 'Fireworks Night',
    category: 'celebration',
    description: 'A dark sky lit by bursts of celebration fireworks.',
    colors: {
      bg1: '#0b0d1f',
      bg2: '#1c1440',
      surface: 'rgba(28,20,64,0.62)',
      text: '#fff8e7',
      muted: '#c0a8d8',
      accent: '#fbbf24',
      accent2: '#f472b6',
      border: 'rgba(251,191,36,0.32)',
    },
    headingFont: 'playfair',
    bodyFont: 'poppins',
    background: 'fireworks',
    decorations: 'sparkles',
    decorDensity: 'high',
    motion: 'sparkle',
    card: 'glass',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#fbbf24', '#f472b6', '#38bdf8', '#ffffff'],
  }),
  defineTheme({
    id: 'party-mode',
    name: 'Party Mode',
    category: 'celebration',
    description: 'Dance-floor lights and bold party typography.',
    colors: {
      bg1: '#12121c',
      bg2: '#262640',
      surface: 'rgba(38,38,64,0.66)',
      text: '#f5f5ff',
      muted: '#a8a8cc',
      accent: '#f43f5e',
      accent2: '#8b5cf6',
      border: 'rgba(244,63,94,0.3)',
    },
    headingFont: 'bebas',
    bodyFont: 'montserrat',
    background: 'disco',
    decorations: 'confetti',
    decorDensity: 'medium',
    motion: 'fall',
    card: 'solid',
    button: 'gradient',
    photo: 'wall',
    confetti: ['#f43f5e', '#8b5cf6', '#22d3ee', '#fbbf24'],
  }),
  defineTheme({
    id: 'disco-fever',
    name: 'Disco Fever',
    category: 'celebration',
    description: 'Mirror-ball glitz and a night that never ends.',
    colors: {
      bg1: '#160b2e',
      bg2: '#3b1063',
      surface: 'rgba(59,16,99,0.62)',
      text: '#fdf4ff',
      muted: '#c4a3e0',
      accent: '#f0abfc',
      accent2: '#facc15',
      border: 'rgba(240,171,252,0.32)',
    },
    headingFont: 'lobster',
    bodyFont: 'poppins',
    background: 'disco',
    decorations: 'sparkles',
    decorDensity: 'high',
    motion: 'sparkle',
    card: 'glass',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#f0abfc', '#facc15', '#38bdf8', '#ffffff'],
  }),

  // ────────────────────────────── ELEGANT ──────────────────────────────
  defineTheme({
    id: 'golden-era',
    name: 'Golden Era',
    category: 'elegant',
    description: 'Old-Hollywood warmth in deep velvet and antique gold.',
    colors: {
      bg1: '#171106',
      bg2: '#33260e',
      surface: 'rgba(51,38,14,0.6)',
      text: '#fbf3dd',
      muted: '#cbb37a',
      accent: '#d4a94e',
      accent2: '#f3dfae',
      border: 'rgba(212,169,78,0.32)',
    },
    headingFont: 'playfair',
    bodyFont: 'montserrat',
    background: 'velvet',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'ornate',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#d4a94e', '#f3dfae', '#ffffff', '#6b5320'],
  }),
  defineTheme({
    id: 'champagne-glow',
    name: 'Champagne Glow',
    category: 'elegant',
    description: 'Warm golden bokeh and toasts to another wonderful year.',
    colors: {
      bg1: '#fdf6e9',
      bg2: '#f0dcb8',
      surface: 'rgba(255,252,244,0.88)',
      text: '#54401e',
      muted: '#9c8256',
      accent: '#c9a227',
      accent2: '#e8c56a',
      border: 'rgba(201,162,39,0.26)',
    },
    headingFont: 'cormorant',
    bodyFont: 'montserrat',
    background: 'bokeh',
    decorations: 'bubbles',
    decorDensity: 'medium',
    motion: 'float',
    card: 'glass',
    button: 'gold',
    photo: 'carousel',
    confetti: ['#c9a227', '#e8c56a', '#fdf6e9', '#b08d57'],
  }),
  defineTheme({
    id: 'minimal-luxe',
    name: 'Minimal Luxe',
    category: 'elegant',
    description: 'Quiet luxury — clean lines, generous space, perfect type.',
    colors: {
      bg1: '#faf9f7',
      bg2: '#ebe8e2',
      surface: 'rgba(255,255,255,0.96)',
      text: '#1f1d1a',
      muted: '#6f6a61',
      accent: '#1f1d1a',
      accent2: '#b8a992',
      border: 'rgba(31,29,26,0.14)',
    },
    headingFont: 'marcellus',
    bodyFont: 'space',
    background: 'clean',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'minimal',
    photo: 'wall',
    confetti: ['#1f1d1a', '#b8a992', '#e5e0d8', '#ffffff'],
  }),
  defineTheme({
    id: 'royal-velvet',
    name: 'Royal Velvet',
    category: 'elegant',
    description: 'Regal purples and gilded frames fit for royalty.',
    colors: {
      bg1: '#180a2e',
      bg2: '#31124f',
      surface: 'rgba(49,18,79,0.62)',
      text: '#f6ecff',
      muted: '#c6a8e0',
      accent: '#d4af37',
      accent2: '#b388ff',
      border: 'rgba(212,175,55,0.32)',
    },
    headingFont: 'cinzel',
    bodyFont: 'cormorant',
    background: 'velvet',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'ornate',
    button: 'gold',
    photo: 'slideshow',
    confetti: ['#d4af37', '#b388ff', '#f6ecff', '#5a2d8a'],
  }),
  defineTheme({
    id: 'premium-slate',
    name: 'Premium Slate',
    category: 'elegant',
    description: 'Graphite tones and restrained metallic accents.',
    colors: {
      bg1: '#14161a',
      bg2: '#232930',
      surface: 'rgba(35,41,48,0.68)',
      text: '#eef1f4',
      muted: '#98a2ad',
      accent: '#9fb3c8',
      accent2: '#d8c9a3',
      border: 'rgba(159,179,200,0.26)',
    },
    headingFont: 'space',
    bodyFont: 'space',
    background: 'velvet',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'outline',
    photo: 'wall',
    confetti: ['#9fb3c8', '#d8c9a3', '#ffffff', '#3a424c'],
  }),

  // ───────────────────────────── FRIENDSHIP ─────────────────────────────
  defineTheme({
    id: 'memories',
    name: 'Memories',
    category: 'friendship',
    description: 'Kraft-paper nostalgia for all the moments you shared.',
    colors: {
      bg1: '#f7f0e3',
      bg2: '#e6d3b3',
      surface: 'rgba(255,251,242,0.94)',
      text: '#4a3a24',
      muted: '#8a7351',
      accent: '#b3763a',
      accent2: '#7d6a4f',
      border: 'rgba(179,118,58,0.26)',
    },
    headingFont: 'marcellus',
    bodyFont: 'quicksand',
    background: 'kraft',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'polaroid',
    button: 'outline',
    photo: 'polaroid',
    confetti: ['#b3763a', '#7d6a4f', '#e6d3b3', '#fffbf2'],
  }),
  defineTheme({
    id: 'polaroid-wall',
    name: 'Polaroid Wall',
    category: 'friendship',
    description: 'Snapshots pinned at playful angles on a bright wall.',
    colors: {
      bg1: '#f4f1ff',
      bg2: '#e0d9f5',
      surface: 'rgba(255,255,255,0.95)',
      text: '#3d3660',
      muted: '#7c74a3',
      accent: '#6d5ae0',
      accent2: '#ff8fab',
      border: 'rgba(109,90,224,0.22)',
    },
    headingFont: 'caveat',
    bodyFont: 'poppins',
    background: 'dots',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'float',
    card: 'polaroid',
    button: 'pill',
    photo: 'polaroid',
    confetti: ['#6d5ae0', '#ff8fab', '#ffd166', '#ffffff'],
  }),
  defineTheme({
    id: 'scrapbook',
    name: 'Scrapbook',
    category: 'friendship',
    description: 'Hand-cut paper notes stacked with warm handwriting.',
    colors: {
      bg1: '#fbf3e4',
      bg2: '#ecd9b8',
      surface: 'rgba(255,252,245,0.95)',
      text: '#443322',
      muted: '#8a6f4e',
      accent: '#cc5f3f',
      accent2: '#4f7942',
      border: 'rgba(204,95,63,0.24)',
    },
    headingFont: 'caveat',
    bodyFont: 'quicksand',
    background: 'kraft',
    decorations: 'notes',
    decorDensity: 'medium',
    motion: 'drift',
    card: 'paper',
    button: 'minimal',
    photo: 'stack',
    confetti: ['#cc5f3f', '#4f7942', '#e8b34a', '#fffbf2'],
  }),
  defineTheme({
    id: 'photo-wall',
    name: 'Photo Wall',
    category: 'friendship',
    description: 'A gallery wall of framed moments in a modern loft.',
    colors: {
      bg1: '#f4f5f7',
      bg2: '#d8dce3',
      surface: 'rgba(255,255,255,0.95)',
      text: '#22262e',
      muted: '#69707d',
      accent: '#334155',
      accent2: '#94a3b8',
      border: 'rgba(51,65,85,0.18)',
    },
    headingFont: 'space',
    bodyFont: 'space',
    background: 'dots',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'minimal',
    photo: 'wall',
    confetti: ['#334155', '#94a3b8', '#ffffff', '#e2e8f0'],
  }),
  defineTheme({
    id: 'handwritten-love',
    name: 'Handwritten Love',
    category: 'friendship',
    description: 'A heartfelt letter on textured notepaper with pressed hearts.',
    colors: {
      bg1: '#fdf4f6',
      bg2: '#f2dee4',
      surface: 'rgba(255,255,255,0.95)',
      text: '#5c3540',
      muted: '#a1737f',
      accent: '#d75d7d',
      accent2: '#b98a5e',
      border: 'rgba(215,93,125,0.22)',
    },
    headingFont: 'caveat',
    bodyFont: 'cormorant',
    background: 'notepaper',
    decorations: 'hearts',
    decorDensity: 'low',
    motion: 'float',
    card: 'paper',
    button: 'pill',
    photo: 'timeline',
    confetti: ['#d75d7d', '#b98a5e', '#f2c4ce', '#ffffff'],
  }),

  // ────────────────────────────── SPECIAL ──────────────────────────────
  defineTheme({
    id: 'eid-glow',
    name: 'Eid Glow',
    category: 'special',
    description: 'Crescent nights, lantern light and geometric elegance.',
    colors: {
      bg1: '#0a1628',
      bg2: '#12304a',
      surface: 'rgba(18,48,74,0.66)',
      text: '#f0f7e8',
      muted: '#9cc0b8',
      accent: '#e6c26b',
      accent2: '#5eead4',
      border: 'rgba(230,194,107,0.3)',
    },
    headingFont: 'amiri',
    bodyFont: 'poppins',
    background: 'geometric',
    decorations: 'stars',
    decorDensity: 'medium',
    motion: 'sparkle',
    card: 'ornate',
    button: 'gold',
    photo: 'carousel',
    confetti: ['#e6c26b', '#5eead4', '#f0f7e8', '#2b6b5e'],
  }),
  defineTheme({
    id: 'geometric-elegance',
    name: 'Geometric Elegance',
    category: 'special',
    description: 'Original arabesque-inspired geometry in ivory and teal.',
    colors: {
      bg1: '#f6faf7',
      bg2: '#d9ece6',
      surface: 'rgba(255,255,255,0.94)',
      text: '#1f3d38',
      muted: '#628078',
      accent: '#0f6b5c',
      accent2: '#c9a227',
      border: 'rgba(15,107,92,0.22)',
    },
    headingFont: 'amiri',
    bodyFont: 'poppins',
    background: 'geometric',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'outline',
    photo: 'timeline',
    confetti: ['#0f6b5c', '#c9a227', '#d9ece6', '#ffffff'],
  }),
  defineTheme({
    id: 'vintage-times',
    name: 'Vintage Times',
    category: 'special',
    description: 'Aged paper warmth and timeless serif charm.',
    colors: {
      bg1: '#f8f1df',
      bg2: '#e8d9b8',
      surface: 'rgba(255,250,238,0.94)',
      text: '#503d22',
      muted: '#8f7550',
      accent: '#96683a',
      accent2: '#6e5a3e',
      border: 'rgba(150,104,58,0.26)',
    },
    headingFont: 'playfair',
    bodyFont: 'cormorant',
    background: 'paper',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'paper',
    button: 'outline',
    photo: 'filmstrip',
    confetti: ['#96683a', '#6e5a3e', '#e8d9b8', '#fffaf0'],
  }),
  defineTheme({
    id: 'retro-wave',
    name: 'Retro Wave',
    category: 'special',
    description: 'Sunset-grid synth nostalgia with chrome type.',
    colors: {
      bg1: '#140a2b',
      bg2: '#3d0f52',
      surface: 'rgba(61,15,82,0.6)',
      text: '#ffe6ff',
      muted: '#c58fe0',
      accent: '#ff6ec7',
      accent2: '#22d3ee',
      border: 'rgba(255,110,199,0.32)',
    },
    headingFont: 'orbitron',
    bodyFont: 'space',
    background: 'neon-grid',
    decorations: 'stars',
    decorDensity: 'low',
    motion: 'drift',
    card: 'neon',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#ff6ec7', '#22d3ee', '#facc15', '#ffffff'],
  }),
  defineTheme({
    id: 'newspaper-press',
    name: 'Newspaper Press',
    category: 'special',
    description: 'Breaking news: another year of greatness. All print, all style.',
    colors: {
      bg1: '#f7f5f0',
      bg2: '#e8e4da',
      surface: 'rgba(255,255,255,0.96)',
      text: '#1c1c1c',
      muted: '#6b6b6b',
      accent: '#111111',
      accent2: '#8c2f2f',
      border: 'rgba(28,28,28,0.18)',
    },
    headingFont: 'playfair',
    bodyFont: 'cormorant',
    background: 'newsprint',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'paper',
    button: 'minimal',
    photo: 'filmstrip',
    confetti: ['#1c1c1c', '#8c2f2f', '#c9c2b4', '#ffffff'],
  }),
  defineTheme({
    id: 'cinematic-film',
    name: 'Cinematic Film',
    category: 'special',
    description: 'Letterboxed frames and projector glow for a premiere night.',
    colors: {
      bg1: '#0c0c0e',
      bg2: '#1c1c22',
      surface: 'rgba(28,28,34,0.68)',
      text: '#f2efe6',
      muted: '#a8a496',
      accent: '#d8c9a3',
      accent2: '#8a8f98',
      border: 'rgba(216,201,163,0.28)',
    },
    headingFont: 'cinzel',
    bodyFont: 'montserrat',
    background: 'film',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'gold',
    photo: 'filmstrip',
    confetti: ['#d8c9a3', '#8a8f98', '#f2efe6', '#3a3a44'],
  }),
  defineTheme({
    id: 'mystery-noir',
    name: 'Mystery Noir',
    category: 'special',
    description: 'A shadowy detective tale where the surprise is the clue.',
    colors: {
      bg1: '#0a0a0c',
      bg2: '#16161c',
      surface: 'rgba(22,22,28,0.7)',
      text: '#e8e6df',
      muted: '#948f82',
      accent: '#c9b458',
      accent2: '#6c6f78',
      border: 'rgba(201,180,88,0.26)',
    },
    headingFont: 'space',
    bodyFont: 'space',
    background: 'spotlight',
    decorations: 'none',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'outline',
    photo: 'stack',
    confetti: ['#c9b458', '#6c6f78', '#e8e6df', '#2a2a32'],
  }),
  defineTheme({
    id: 'surprise-box',
    name: 'Surprise Box',
    category: 'special',
    description: 'The ultimate gift-unboxing rush in playful colors.',
    colors: {
      bg1: '#fff3f6',
      bg2: '#ffd6e2',
      surface: 'rgba(255,255,255,0.93)',
      text: '#5c1f3a',
      muted: '#a85d7e',
      accent: '#ff3d81',
      accent2: '#8b5cf6',
      border: 'rgba(255,61,129,0.26)',
    },
    headingFont: 'lobster',
    bodyFont: 'quicksand',
    background: 'soft-glow',
    decorations: 'confetti',
    decorDensity: 'high',
    motion: 'fall',
    card: 'glass',
    button: 'gradient',
    photo: 'stack',
    confetti: ['#ff3d81', '#8b5cf6', '#ffd166', '#4ade80'],
  }),
];
