import { defineTheme } from '../define';

/**
 * Part 2 — Gaming (5), Space (5), Nature (6) = 16 themes.
 * All palettes and artwork are original compositions.
 */

export const PART2_THEMES = [
  // ────────────────────────────── GAMING ──────────────────────────────
  defineTheme({
    id: 'neon-gaming',
    name: 'Neon Gaming',
    category: 'gaming',
    description: 'RGB-lit arena with electric borders and glow effects.',
    colors: {
      bg1: '#0a0618',
      bg2: '#1a0b3a',
      surface: 'rgba(26,11,58,0.66)',
      text: '#f0e9ff',
      muted: '#a88fd9',
      accent: '#b026ff',
      accent2: '#00ffc8',
      border: 'rgba(176,38,255,0.34)',
    },
    headingFont: 'orbitron',
    bodyFont: 'space',
    background: 'neon-grid',
    decorations: 'sparkles',
    decorDensity: 'medium',
    motion: 'sparkle',
    card: 'neon',
    button: 'neon',
    photo: 'carousel',
    confetti: ['#b026ff', '#00ffc8', '#ff2e97', '#ffffff'],
  }),
  defineTheme({
    id: 'arcade-cabinet',
    name: 'Arcade Cabinet',
    category: 'gaming',
    description: 'Retro cabinet glow with scanlines and pixel-perfect type.',
    colors: {
      bg1: '#12081f',
      bg2: '#2b0f3d',
      surface: 'rgba(43,15,61,0.72)',
      text: '#ffe9fb',
      muted: '#c98fd2',
      accent: '#ff2e97',
      accent2: '#ffd166',
      border: 'rgba(255,46,151,0.32)',
    },
    headingFont: 'pixel',
    bodyFont: 'space',
    background: 'scanlines',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'pixel',
    button: 'pixel',
    photo: 'wall',
    confetti: ['#ff2e97', '#ffd166', '#00ffc8', '#6bd3ff'],
  }),
  defineTheme({
    id: 'pixel-quest',
    name: 'Pixel Quest',
    category: 'gaming',
    description: '8-bit adventure map with blocky frames and stacked cards.',
    colors: {
      bg1: '#0f1a2e',
      bg2: '#1d3557',
      surface: 'rgba(29,53,87,0.75)',
      text: '#eaf4ff',
      muted: '#9db8d9',
      accent: '#57cc99',
      accent2: '#ffd166',
      border: 'rgba(87,204,153,0.32)',
    },
    headingFont: 'pixel',
    bodyFont: 'space',
    background: 'pixel-grid',
    decorations: 'stars',
    decorDensity: 'low',
    motion: 'drift',
    card: 'pixel',
    button: 'pixel',
    photo: 'stack',
    confetti: ['#57cc99', '#ffd166', '#6bd3ff', '#ff8fab'],
  }),
  defineTheme({
    id: 'cyber-circuit',
    name: 'Cyber Circuit',
    category: 'gaming',
    description: 'Motherboard traces and holographic accents.',
    colors: {
      bg1: '#04121a',
      bg2: '#082b33',
      surface: 'rgba(8,43,51,0.66)',
      text: '#dffbff',
      muted: '#7fc4c9',
      accent: '#00ffd0',
      accent2: '#36c5ff',
      border: 'rgba(0,255,208,0.3)',
    },
    headingFont: 'space',
    bodyFont: 'space',
    background: 'circuit',
    decorations: 'sparkles',
    decorDensity: 'low',
    motion: 'sparkle',
    card: 'neon',
    button: 'neon',
    photo: 'wall',
    confetti: ['#00ffd0', '#36c5ff', '#dffbff', '#0e5c66'],
  }),
  defineTheme({
    id: 'controller-club',
    name: 'Controller Club',
    category: 'gaming',
    description: 'Cozy couch co-op vibe with soft glass panels.',
    colors: {
      bg1: '#1c2333',
      bg2: '#2f3b59',
      surface: 'rgba(47,59,89,0.62)',
      text: '#eef2ff',
      muted: '#a3b0d1',
      accent: '#7c9cff',
      accent2: '#ff8fab',
      border: 'rgba(124,156,255,0.3)',
    },
    headingFont: 'montserrat',
    bodyFont: 'space',
    background: 'dots',
    decorations: 'bubbles',
    decorDensity: 'low',
    motion: 'rise',
    card: 'glass',
    button: 'gradient',
    photo: 'carousel',
    confetti: ['#7c9cff', '#ff8fab', '#ffe9a8', '#eef2ff'],
  }),

  // ────────────────────────────── SPACE ──────────────────────────────
  defineTheme({
    id: 'galaxy',
    name: 'Galaxy',
    category: 'space',
    description: 'Deep nebula clouds and a cosmic photo carousel.',
    colors: {
      bg1: '#0b0724',
      bg2: '#231b54',
      surface: 'rgba(35,27,84,0.6)',
      text: '#f2eeff',
      muted: '#b0a4e3',
      accent: '#8b7bff',
      accent2: '#ff9ec7',
      border: 'rgba(139,123,255,0.32)',
    },
    headingFont: 'marcellus',
    bodyFont: 'space',
    background: 'nebula',
    decorations: 'stars',
    decorDensity: 'high',
    motion: 'sparkle',
    card: 'glass',
    button: 'gradient',
    photo: 'carousel',
    confetti: ['#8b7bff', '#ff9ec7', '#5eead4', '#ffffff'],
  }),
  defineTheme({
    id: 'starfield',
    name: 'Starfield',
    category: 'space',
    description: 'Quiet constellations framing a gentle filmstrip of memories.',
    colors: {
      bg1: '#050510',
      bg2: '#101028',
      surface: 'rgba(16,16,40,0.6)',
      text: '#e8e8ff',
      muted: '#9c9cc9',
      accent: '#c0c8ff',
      accent2: '#8b7bff',
      border: 'rgba(192,200,255,0.28)',
    },
    headingFont: 'cormorant',
    bodyFont: 'space',
    background: 'stars',
    decorations: 'stars',
    decorDensity: 'medium',
    motion: 'sparkle',
    card: 'minimal',
    button: 'outline',
    photo: 'filmstrip',
    confetti: ['#c0c8ff', '#8b7bff', '#ffffff', '#4a4a8a'],
  }),
  defineTheme({
    id: 'cosmic-dust',
    name: 'Cosmic Dust',
    category: 'space',
    description: 'Stardust trails across a celestial timeline.',
    colors: {
      bg1: '#140a2e',
      bg2: '#3b1d6e',
      surface: 'rgba(59,29,110,0.6)',
      text: '#f6ecff',
      muted: '#c2a8e8',
      accent: '#e879f9',
      accent2: '#a78bfa',
      border: 'rgba(232,121,249,0.3)',
    },
    headingFont: 'cinzel',
    bodyFont: 'poppins',
    background: 'nebula',
    decorations: 'sparkles',
    decorDensity: 'medium',
    motion: 'sparkle',
    card: 'glass',
    button: 'gradient',
    photo: 'timeline',
    confetti: ['#e879f9', '#a78bfa', '#ffffff', '#6420a8'],
  }),
  defineTheme({
    id: 'moonlight',
    name: 'Moonlight',
    category: 'space',
    description: 'Silver moonlight rippling over midnight blues.',
    colors: {
      bg1: '#0a1228',
      bg2: '#1b2b52',
      surface: 'rgba(27,43,82,0.62)',
      text: '#edf3ff',
      muted: '#9fb4d8',
      accent: '#dbe7ff',
      accent2: '#7c9cff',
      border: 'rgba(219,231,255,0.28)',
    },
    headingFont: 'cormorant',
    bodyFont: 'montserrat',
    background: 'moon',
    decorations: 'stars',
    decorDensity: 'low',
    motion: 'float',
    card: 'minimal',
    button: 'outline',
    photo: 'slideshow',
    confetti: ['#dbe7ff', '#7c9cff', '#ffffff', '#2b3f6e'],
  }),
  defineTheme({
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    category: 'space',
    description: 'Shimmering polar lights dancing over a silent horizon.',
    colors: {
      bg1: '#04101c',
      bg2: '#0a2840',
      surface: 'rgba(10,40,64,0.6)',
      text: '#e6fff9',
      muted: '#8fc9c0',
      accent: '#4ade80',
      accent2: '#22d3ee',
      border: 'rgba(74,222,128,0.3)',
    },
    headingFont: 'space',
    bodyFont: 'space',
    background: 'aurora',
    decorations: 'stars',
    decorDensity: 'medium',
    motion: 'drift',
    card: 'glass',
    button: 'gradient',
    photo: 'carousel',
    confetti: ['#4ade80', '#22d3ee', '#a78bfa', '#ffffff'],
  }),

  // ────────────────────────────── NATURE ──────────────────────────────
  defineTheme({
    id: 'forest-whisper',
    name: 'Forest Whisper',
    category: 'nature',
    description: 'Quiet woodland greens with fluttering leaves and paper cards.',
    colors: {
      bg1: '#eef4e9',
      bg2: '#c9dcc0',
      surface: 'rgba(255,255,252,0.92)',
      text: '#2c3a26',
      muted: '#64745a',
      accent: '#4f7942',
      accent2: '#a3b18a',
      border: 'rgba(79,121,66,0.24)',
    },
    headingFont: 'marcellus',
    bodyFont: 'quicksand',
    background: 'mountains',
    decorations: 'leaves',
    decorDensity: 'medium',
    motion: 'sway',
    card: 'paper',
    button: 'outline',
    photo: 'timeline',
    confetti: ['#4f7942', '#a3b18a', '#dde5b6', '#f4f9e9'],
  }),
  defineTheme({
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'nature',
    description: 'Golden-hour warmth with drifting embers and polaroids.',
    colors: {
      bg1: '#fff1e0',
      bg2: '#ffc9a3',
      surface: 'rgba(255,252,246,0.9)',
      text: '#5a2d1a',
      muted: '#a96f4e',
      accent: '#f97316',
      accent2: '#fbbf24',
      border: 'rgba(249,115,22,0.24)',
    },
    headingFont: 'playfair',
    bodyFont: 'poppins',
    background: 'sunset',
    decorations: 'embers',
    decorDensity: 'medium',
    motion: 'rise',
    card: 'solid',
    button: 'gradient',
    photo: 'polaroid',
    confetti: ['#f97316', '#fbbf24', '#ff8fab', '#fff1e0'],
  }),
  defineTheme({
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'nature',
    description: 'Calm coastal blues with rolling waves and soft bubbles.',
    colors: {
      bg1: '#e8f7fb',
      bg2: '#b8e6f2',
      surface: 'rgba(255,255,255,0.9)',
      text: '#134a5c',
      muted: '#5e93a6',
      accent: '#0891b2',
      accent2: '#22d3ee',
      border: 'rgba(8,145,178,0.22)',
    },
    headingFont: 'quicksand',
    bodyFont: 'quicksand',
    background: 'waves',
    decorations: 'bubbles',
    decorDensity: 'medium',
    motion: 'rise',
    card: 'glass',
    button: 'pill',
    photo: 'carousel',
    confetti: ['#0891b2', '#22d3ee', '#a5f3fc', '#ffffff'],
  }),
  defineTheme({
    id: 'wild-flowers',
    name: 'Wild Flowers',
    category: 'nature',
    description: 'A meadow of blooms pressed into a keepsake polaroid album.',
    colors: {
      bg1: '#fdf8fa',
      bg2: '#f3e3ec',
      surface: 'rgba(255,255,255,0.92)',
      text: '#4d3345',
      muted: '#93718a',
      accent: '#c85c9c',
      accent2: '#e8b34a',
      border: 'rgba(200,92,156,0.22)',
    },
    headingFont: 'greatvibes',
    bodyFont: 'cormorant',
    background: 'floral',
    decorations: 'petals',
    decorDensity: 'medium',
    motion: 'fall',
    card: 'paper',
    button: 'outline',
    photo: 'polaroid',
    confetti: ['#c85c9c', '#e8b34a', '#8fae7e', '#ffffff'],
  }),
  defineTheme({
    id: 'mountain-mist',
    name: 'Mountain Mist',
    category: 'nature',
    description: 'Layered peaks fading into mist with a quiet filmstrip.',
    colors: {
      bg1: '#edf1f4',
      bg2: '#c3ced8',
      surface: 'rgba(255,255,255,0.9)',
      text: '#2b3742',
      muted: '#66788a',
      accent: '#4a6b8a',
      accent2: '#9db4c7',
      border: 'rgba(74,107,138,0.22)',
    },
    headingFont: 'marcellus',
    bodyFont: 'space',
    background: 'mountains',
    decorations: 'clouds',
    decorDensity: 'low',
    motion: 'drift',
    card: 'minimal',
    button: 'outline',
    photo: 'filmstrip',
    confetti: ['#4a6b8a', '#9db4c7', '#e2e9ef', '#ffffff'],
  }),
  defineTheme({
    id: 'tropical-paradise',
    name: 'Tropical Paradise',
    category: 'nature',
    description: 'Sun-drenched palms, bright rays and a lively photo wall.',
    colors: {
      bg1: '#fffbe8',
      bg2: '#ffe9b3',
      surface: 'rgba(255,255,255,0.9)',
      text: '#1e4e3a',
      muted: '#5b8a6e',
      accent: '#16a34a',
      accent2: '#f59e0b',
      border: 'rgba(22,163,74,0.24)',
    },
    headingFont: 'lobster',
    bodyFont: 'quicksand',
    background: 'sun-rays',
    decorations: 'leaves',
    decorDensity: 'medium',
    motion: 'sway',
    card: 'solid',
    button: 'gradient',
    photo: 'wall',
    confetti: ['#16a34a', '#f59e0b', '#22d3ee', '#ffffff'],
  }),
];
